package com.example.flagguesse_final

import androidx.compose.runtime.Immutable

class Data {

    val countryCodes = listOf(
        "AD", "AE", "AF", "AG", "AI", "AL", "AM", "AO", "AQ", "AR", "AS", "AT", "AU", "AW", "AX", "AZ", "BA", "BB", "BD", "BE",
        "BF", "BG", "BH", "BI", "BJ", "BL", "BM", "BN", "BO", "BQ", "BR", "BS", "BT", "BV", "BW", "BY", "BZ", "CA", "CC", "CD",
        "CF", "CG", "CH", "CI", "CK", "CL", "CM", "CN", "CO", "CR", "CU", "CV", "CW", "CX", "CY", "CZ", "DE", "DJ", "DK", "DM",
        "DO_1", "DZ", "EC", "EE", "EG", "EH", "ER", "ES", "ET", "EU", "FI", "FJ", "FK", "FM", "FO", "FR", "GA", "GB_ENG", "GB_NIR",
        "GB_SCT1", "GB_WLS", "GB", "GD", "GE", "GF", "GG", "GH", "GI", "GL", "GM", "GN", "GP", "GQ", "GR", "GS", "GT", "GU", "GW",
        "GY", "HK", "HM", "HN", "HR", "HT", "HU", "ID", "IE", "IL", "IM", "IN", "IO", "IQ", "IR", "IS", "IT", "JE", "JM", "JO",
        "JP", "KE", "KG", "KH", "KI", "KM", "KN", "KP", "KR", "KW", "KY", "KZ", "LA", "LB", "LC", "LI", "LK", "LR", "LS", "LT",
        "LU", "LV", "LY", "MA", "MC", "MD", "ME", "MF", "MG", "MH", "MK", "ML", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT",
        "MU", "MV", "MW", "MX", "MY", "MZ", "NA", "NC", "NE", "NF", "NG", "NI", "NL", "NO", "NP", "NR", "NU", "NZ", "OM", "PA",
        "PE", "PF", "PG", "PH", "PK", "PL", "PM", "PN", "PR", "PS", "PT", "PW", "PY", "QA", "RE", "RO", "RS", "RU", "RW", "SA",
        "SB", "SC", "SD", "SE", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SR", "SS", "ST", "SV", "SX", "SY", "SZ",
        "TC", "TD", "TF", "TG", "TH", "TJ", "TK", "TL", "TM", "TN", "TO", "TR", "TT", "TV", "TW", "TZ", "UA", "UG", "UM", "US",
        "UY", "UZ", "VA", "VC", "VE", "VG", "VI", "VN", "VU", "WF", "WS", "XK", "YE", "YT", "ZA", "ZM", "ZW"
    )


    val countryFlags = mapOf(
        "AD" to R.drawable.ad,
        "AE" to R.drawable.ae,
        "AF" to R.drawable.af,
        "AG" to R.drawable.ag,
        "AI" to R.drawable.ai,
        "AL" to R.drawable.al,
        "AM" to R.drawable.am,
        "AO" to R.drawable.ao,
        "AQ" to R.drawable.aq,
        "AR" to R.drawable.ar,
        "AS" to R.drawable.`as`,
        "AT" to R.drawable.at,
        "AU" to R.drawable.au,
        "AW" to R.drawable.aw,
        "AX" to R.drawable.ax,
        "AZ" to R.drawable.az,
        "BA" to R.drawable.ba,
        "BB" to R.drawable.bb,
        "BD" to R.drawable.bd,
        "BE" to R.drawable.be,
        "BF" to R.drawable.bf,
        "BG" to R.drawable.bg,
        "BH" to R.drawable.bh,
        "BI" to R.drawable.bi,
        "BJ" to R.drawable.bj,
        "BL" to R.drawable.bl,
        "BM" to R.drawable.bm,
        "BN" to R.drawable.bn,
        "BO" to R.drawable.bo,
        "BQ" to R.drawable.bq,
        "BR" to R.drawable.br,
        "BS" to R.drawable.bs,
        "BT" to R.drawable.bt,
        "BV" to R.drawable.bv,
        "BW" to R.drawable.bw,
        "BY" to R.drawable.by,
        "BZ" to R.drawable.bz,
        "CA" to R.drawable.ca,
        "CC" to R.drawable.cc,
        "CD" to R.drawable.cd,
        "CF" to R.drawable.cf,
        "CG" to R.drawable.cg,
        "CH" to R.drawable.ch,
        "CI" to R.drawable.ci,
        "CK" to R.drawable.ck,
        "CL" to R.drawable.cl,
        "CM" to R.drawable.cm,
        "CN" to R.drawable.cn,
        "CO" to R.drawable.co,
        "CR" to R.drawable.cr,
        "CU" to R.drawable.cu,
        "CV" to R.drawable.cv,
        "CW" to R.drawable.cw,
        "CX" to R.drawable.cx,
        "CY" to R.drawable.cy,
        "CZ" to R.drawable.cz,
        "DE" to R.drawable.de,
        "DJ" to R.drawable.dj,
        "DK" to R.drawable.dk,
        "DM" to R.drawable.dm,
        "DO_1" to R.drawable.do_1,
        "DZ" to R.drawable.dz,
        "EC" to R.drawable.ec,
        "EE" to R.drawable.ee,
        "EG" to R.drawable.eg,
        "EH" to R.drawable.eh,
        "ER" to R.drawable.er,
        "ES" to R.drawable.es,
        "ET" to R.drawable.et,
        "EU" to R.drawable.eu,
        "FI" to R.drawable.fi,
        "FJ" to R.drawable.fj,
        "FK" to R.drawable.fk,
        "FM" to R.drawable.fm,
        "FO" to R.drawable.fo,
        "FR" to R.drawable.fr,
        "GA" to R.drawable.ga,
        "GB_ENG" to R.drawable.gb_eng,
        "GB_NIR" to R.drawable.gb_nir,
        "GB_SCT1" to R.drawable.gb_sct1,
        "GB_WLS" to R.drawable.gb_wls,
        "GB" to R.drawable.gb,
        "GD" to R.drawable.gd1,
        "GE" to R.drawable.ge,
        "GF" to R.drawable.gf,
        "GG" to R.drawable.gg,
        "GH" to R.drawable.gh,
        "GI" to R.drawable.gi,
        "GL" to R.drawable.gl,
        "GM" to R.drawable.gm,
        "GN" to R.drawable.gn,
        "GP" to R.drawable.gp,
        "GQ" to R.drawable.gq,
        "GR" to R.drawable.gr,
        "GS" to R.drawable.gs,
        "GT" to R.drawable.gt,
        "GU" to R.drawable.gu,
        "GW" to R.drawable.gw,
        "GY" to R.drawable.gy,
        "HK" to R.drawable.hk,
        "HM" to R.drawable.hm,
        "HN" to R.drawable.hn,
        "HR" to R.drawable.hr,
        "HT" to R.drawable.ht,
        "HU" to R.drawable.hu,
        "ID" to R.drawable.id,
        "IE" to R.drawable.ie,
        "IL" to R.drawable.il,
        "IM" to R.drawable.im,
        "IN" to R.drawable.`in`,
        "IO" to R.drawable.io,
        "IQ" to R.drawable.iq,
        "IR" to R.drawable.ir,
        "IS" to R.drawable.`is`,
        "IT" to R.drawable.it,
        "JE" to R.drawable.je,
        "JM" to R.drawable.jm,
        "JO" to R.drawable.jo,
        "JP" to R.drawable.jp,
        "KE" to R.drawable.ke,
        "KG" to R.drawable.kg,
        "KH" to R.drawable.kh,
        "KI" to R.drawable.ki,
        "KM" to R.drawable.km,
        "KN" to R.drawable.kn,
        "KP" to R.drawable.kp,
        "KR" to R.drawable.kr,
        "KW" to R.drawable.kw,
        "KY" to R.drawable.ky,
        "KZ" to R.drawable.kz,
        "LA" to R.drawable.la,
        "LB" to R.drawable.lb,
        "LC" to R.drawable.lc,
        "LI" to R.drawable.li,
        "LK" to R.drawable.lk,
        "LR" to R.drawable.lr,
        "LS" to R.drawable.ls,
        "LT" to R.drawable.lt,
        "LU" to R.drawable.lu,
        "LV" to R.drawable.lv,
        "LY" to R.drawable.ly,
        "MA" to R.drawable.ma,
        "MC" to R.drawable.mc,
        "MD" to R.drawable.md,
        "ME" to R.drawable.me,
        "MF" to R.drawable.mf,
        "MG" to R.drawable.mg,
        "MH" to R.drawable.mh,
        "MK" to R.drawable.mk,
        "ML" to R.drawable.ml,
        "MM" to R.drawable.mm,
        "MN" to R.drawable.mn,
        "MO" to R.drawable.mo,
        "MP" to R.drawable.mp,
        "MQ" to R.drawable.mq,
        "MR" to R.drawable.mr,
        "MS" to R.drawable.ms,
        "MT" to R.drawable.mt,
        "MU" to R.drawable.mu,
        "MV" to R.drawable.mv,
        "MW" to R.drawable.mw,
        "MX" to R.drawable.mx,
        "MY" to R.drawable.my,
        "MZ" to R.drawable.mz,
        "NA" to R.drawable.na,
        "NC" to R.drawable.nc,
        "NE" to R.drawable.ne,
        "NF" to R.drawable.nf,
        "NG" to R.drawable.ng,
        "NI" to R.drawable.ni,
        "NL" to R.drawable.nl,
        "NO" to R.drawable.no,
        "NP" to R.drawable.np,
        "NR" to R.drawable.nr,
        "NU" to R.drawable.nu,
        "NZ" to R.drawable.nz,
        "OM" to R.drawable.om,
        "PA" to R.drawable.pa,
        "PE" to R.drawable.pe,
        "PF" to R.drawable.pf,
        "PG" to R.drawable.pg,
        "PH" to R.drawable.ph,
        "PK" to R.drawable.pk,
        "PL" to R.drawable.pl,
        "PM" to R.drawable.pm,
        "PN" to R.drawable.pn,
        "PR" to R.drawable.pr,
        "PS" to R.drawable.ps,
        "PT" to R.drawable.pt,
        "PW" to R.drawable.pw,
        "PY" to R.drawable.py,
        "QA" to R.drawable.qa,
        "RE" to R.drawable.re,
        "RO" to R.drawable.ro,
        "RS" to R.drawable.rs,
        "RU" to R.drawable.ru,
        "RW" to R.drawable.rw,
        "SA" to R.drawable.sa,
        "SB" to R.drawable.sb,
        "SC" to R.drawable.sc,
        "SD" to R.drawable.sd,
        "SE" to R.drawable.se,
        "SG" to R.drawable.sg,
        "SH" to R.drawable.sh,
        "SI" to R.drawable.si,
        "SJ" to R.drawable.sj,
        "SK" to R.drawable.sk,
        "SL" to R.drawable.sl,
        "SM" to R.drawable.sm,
        "SN" to R.drawable.sn,
        "SO" to R.drawable.so,
        "SR" to R.drawable.sr,
        "SS" to R.drawable.ss,
        "ST" to R.drawable.st,
        "SV" to R.drawable.sv,
        "SX" to R.drawable.sx,
        "SY" to R.drawable.sy,
        "SZ" to R.drawable.sz,
        "TC" to R.drawable.tc,
        "TD" to R.drawable.td,
        "TF" to R.drawable.tf,
        "TG" to R.drawable.tg,
        "TH" to R.drawable.th,
        "TJ" to R.drawable.tj,
        "TK" to R.drawable.tk,
        "TL" to R.drawable.tl,
        "TM" to R.drawable.tm,
        "TN" to R.drawable.tn,
        "TO" to R.drawable.to,
        "TR" to R.drawable.tr,
        "TT" to R.drawable.tt,
        "TV" to R.drawable.tv,
        "TW" to R.drawable.tw,
        "TZ" to R.drawable.tz,
        "UA" to R.drawable.ua,
        "UG" to R.drawable.ug,
        "UM" to R.drawable.um,
        "US" to R.drawable.us,
        "UY" to R.drawable.uy,
        "UZ" to R.drawable.uz,
        "VA" to R.drawable.va,
        "VC" to R.drawable.vc,
        "VE" to R.drawable.ve,
        "VG" to R.drawable.vg,
        "VI" to R.drawable.vi,
        "VN" to R.drawable.vn,
        "VU" to R.drawable.vu,
        "WF" to R.drawable.wf,
        "WS" to R.drawable.ws,
        "XK" to R.drawable.xk,
        "YE" to R.drawable.ye,
        "YT" to R.drawable.yt,
        "ZA" to R.drawable.za,
        "ZM" to R.drawable.zm,
        "ZW" to R.drawable.zw
    )


    val country_names = mapOf(
        "AD" to "Andorra",
        "AE" to "United Arab Emirates",
        "AF" to "Afghanistan",
        "AG" to "Antigua and Barbuda",
        "AI" to "Anguilla",
        "AL" to "Albania",
        "AM" to "Armenia",
        "AO" to "Angola",
        "AQ" to "Antarctica",
        "AR" to "Argentina",
        "AS" to "American Samoa",
        "AT" to "Austria",
        "AU" to "Australia",
        "AW" to "Aruba",
        "AX" to "Åland Islands",
        "AZ" to "Azerbaijan",
        "BA" to "Bosnia and Herzegovina",
        "BB" to "Barbados",
        "BD" to "Bangladesh",
        "BE" to "Belgium",
        "BF" to "Burkina Faso",
        "BG" to "Bulgaria",
        "BH" to "Bahrain",
        "BI" to "Burundi",
        "BJ" to "Benin",
        "BL" to "Saint Barthélemy",
        "BM" to "Bermuda",
        "BN" to "Brunei Darussalam",
        "BO" to "Bolivia, Plurinational State of",
        "BQ" to "Caribbean Netherlands",
        "BR" to "Brazil",
        "BS" to "Bahamas",
        "BT" to "Bhutan",
        "BV" to "Bouvet Island",
        "BW" to "Botswana",
        "BY" to "Belarus",
        "BZ" to "Belize",
        "CA" to "Canada",
        "CC" to "Cocos (Keeling) Islands",
        "CD" to "Congo, the Democratic Republic of the",
        "CF" to "Central African Republic",
        "CG" to "Republic of the Congo",
        "CH" to "Switzerland",
        "CI" to "Côte d'Ivoire",
        "CK" to "Cook Islands",
        "CL" to "Chile",
        "CM" to "Cameroon",
        "CN" to "China (People's Republic of China)",
        "CO" to "Colombia",
        "CR" to "Costa Rica",
        "CU" to "Cuba",
        "CV" to "Cape Verde",
        "CW" to "Curaçao",
        "CX" to "Christmas Island",
        "CY" to "Cyprus",
        "CZ" to "Czech Republic",
        "DE" to "Germany",
        "DJ" to "Djibouti",
        "DK" to "Denmark",
        "DM" to "Dominica",
        "DO_1" to "Dominican Republic",
        "DZ" to "Algeria",
        "EC" to "Ecuador",
        "EE" to "Estonia",
        "EG" to "Egypt",
        "EH" to "Western Sahara",
        "ER" to "Eritrea",
        "ES" to "Spain",
        "ET" to "Ethiopia",
        "EU" to "Europe",
        "FI" to "Finland",
        "FJ" to "Fiji",
        "FK" to "Falkland Islands (Malvinas)",
        "FM" to "Micronesia, Federated States of",
        "FO" to "Faroe Islands",
        "FR" to "France",
        "GA" to "Gabon",
        "GB_ENG" to "England",
        "GB_NIR" to "Northern Ireland",
        "GB_SCT1" to "Scotland",
        "GB_WLS" to "Wales",
        "GB" to "United Kingdom",
        "GD" to "Grenada",
        "GE" to "Georgia",
        "GF" to "French Guiana",
        "GG" to "Guernsey",
        "GH" to "Ghana",
        "GI" to "Gibraltar",
        "GL" to "Greenland",
        "GM" to "Gambia",
        "GN" to "Guinea",
        "GP" to "Guadeloupe",
        "GQ" to "Equatorial Guinea",
        "GR" to "Greece",
        "GS" to "South Georgia and the South Sandwich Islands",
        "GT" to "Guatemala",
        "GU" to "Guam",
        "GW" to "Guinea-Bissau",
        "GY" to "Guyana",
        "HK" to "Hong Kong",
        "HM" to "Heard Island and McDonald Islands",
        "HN" to "Honduras",
        "HR" to "Croatia",
        "HT" to "Haiti",
        "HU" to "Hungary",
        "ID" to "Indonesia",
        "IE" to "Ireland",
        "IL" to "Israel",
        "IM" to "Isle of Man",
        "IN" to "India",
        "IO" to "British Indian Ocean Territory",
        "IQ" to "Iraq",
        "IR" to "Iran, Islamic Republic of",
        "IS" to "Iceland",
        "IT" to "Italy",
        "JE" to "Jersey",
        "JM" to "Jamaica",
        "JO" to "Jordan",
        "JP" to "Japan",
        "KE" to "Kenya",
        "KG" to "Kyrgyzstan",
        "KH" to "Cambodia",
        "KI" to "Kiribati",
        "KM" to "Comoros",
        "KN" to "Saint Kitts and Nevis",
        "KP" to "Korea, Democratic People's Republic of",
        "KR" to "Korea, Republic of",
        "KW" to "Kuwait",
        "KY" to "Cayman Islands",
        "KZ" to "Kazakhstan",
        "LA" to "Laos (Lao People's Democratic Republic)",
        "LB" to "Lebanon",
        "LC" to "Saint Lucia",
        "LI" to "Liechtenstein",
        "LK" to "Sri Lanka",
        "LR" to "Liberia",
        "LS" to "Lesotho",
        "LT" to "Lithuania",
        "LU" to "Luxembourg",
        "LV" to "Latvia",
        "LY" to "Libya",
        "MA" to "Morocco",
        "MC" to "Monaco",
        "MD" to "Moldova, Republic of",
        "ME" to "Montenegro",
        "MF" to "Saint Martin",
        "MG" to "Madagascar",
        "MH" to "Marshall Islands",
        "MK" to "North Macedonia",
        "ML" to "Mali",
        "MM" to "Myanmar",
        "MN" to "Mongolia",
        "MO" to "Macao",
        "MP" to "Northern Mariana Islands",
        "MQ" to "Martinique",
        "MR" to "Mauritania",
        "MS" to "Montserrat",
        "MT" to "Malta",
        "MU" to "Mauritius",
        "MV" to "Maldives",
        "MW" to "Malawi",
        "MX" to "Mexico",
        "MY" to "Malaysia",
        "MZ" to "Mozambique",
        "NA" to "Namibia",
        "NC" to "New Caledonia",
        "NE" to "Niger",
        "NF" to "Norfolk Island",
        "NG" to "Nigeria",
        "NI" to "Nicaragua",
        "NL" to "Netherlands",
        "NO" to "Norway",
        "NP" to "Nepal",
        "NR" to "Nauru",
        "NU" to "Niue",
        "NZ" to "New Zealand",
        "OM" to "Oman",
        "PA" to "Panama",
        "PE" to "Peru",
        "PF" to "French Polynesia",
        "PG" to "Papua New Guinea",
        "PH" to "Philippines",
        "PK" to "Pakistan",
        "PL" to "Poland",
        "PM" to "Saint Pierre and Miquelon",
        "PN" to "Pitcairn",
        "PR" to "Puerto Rico",
        "PS" to "Palestine",
        "PT" to "Portugal",
        "PW" to "Palau",
        "PY" to "Paraguay",
        "QA" to "Qatar",
        "RE" to "Réunion",
        "RO" to "Romania",
        "RS" to "Serbia",
        "RU" to "Russian Federation",
        "RW" to "Rwanda",
        "SA" to "Saudi Arabia",
        "SB" to "Solomon Islands",
        "SC" to "Seychelles",
        "SD" to "Sudan",
        "SE" to "Sweden",
        "SG" to "Singapore",
        "SH" to "Saint Helena, Ascension and Tristan da Cunha",
        "SI" to "Slovenia",
        "SJ" to "Svalbard and Jan Mayen Islands",
        "SK" to "Slovakia",
        "SL" to "Sierra Leone",
        "SM" to "San Marino",
        "SN" to "Senegal",
        "SO" to "Somalia",
        "SR" to "Suriname",
        "SS" to "South Sudan",
        "ST" to "Sao Tome and Principe",
        "SV" to "El Salvador",
        "SX" to "Sint Maarten (Dutch part)",
        "SY" to "Syrian Arab Republic",
        "SZ" to "Swaziland",
        "TC" to "Turks and Caicos Islands",
        "TD" to "Chad",
        "TF" to "French Southern Territories",
        "TG" to "Togo",
        "TH" to "Thailand",
        "TJ" to "Tajikistan",
        "TK" to "Tokelau",
        "TL" to "Timor-Leste",
        "TM" to "Turkmenistan",
        "TN" to "Tunisia",
        "TO" to "Tonga",
        "TR" to "Turkey",
        "TT" to "Trinidad and Tobago",
        "TV" to "Tuvalu",
        "TW" to "Taiwan (Republic of China)",
        "TZ" to "Tanzania, United Republic of",
        "UA" to "Ukraine",
        "UG" to "Uganda",
        "UM" to "US Minor Outlying Islands",
        "US" to "United States",
        "UY" to "Uruguay",
        "UZ" to "Uzbekistan",
        "VA" to "Holy See (Vatican City State)",
        "VC" to "Saint Vincent and the Grenadines",
        "VE" to "Venezuela, Bolivarian Republic of",
        "VG" to "Virgin Islands, British",
        "VI" to "Virgin Islands, U.S.",
        "VN" to "Vietnam",
        "VU" to "Vanuatu",
        "WF" to "Wallis and Futuna Islands",
        "WS" to "Samoa",
        "XK" to "Kosovo",
        "YE" to "Yemen",
        "YT" to "Mayotte",
        "ZA" to "South Africa",
        "ZM" to "Zambia",
        "ZW" to "Zimbabwe"
    )

}